routes/web.php
<?php

use App\Models\Shipment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

// Route::get('/mail', function () {
//     $shipment = Shipment::find(16);
//     $mailType = 'vendor';
//     return view('email.free-quote-mail', compact('shipment', 'mailType'));
// });



Route::group(['namespace' => 'App\Http\Controllers'], function () {
    Route::get('/autologin', 'Auth\LoginController@autoLogin');

    Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        /* User Management */
        Route::get('/users', 'UserController@index')->name('user.index');
        Route::get('/user/login/{id}', 'UserController@userLogin')->name('user.login');
        Route::get('/user/logout/', 'UserController@userLogout')->name('user.logout');
        Route::get('/user/create/{id?}', 'UserController@createOrEdit')->name('user.createOrEdit');
        Route::post('/user/store/{id?}', 'UserController@store')->name('user.store');
        Route::delete('/user/{id}/destroy', 'UserController@destroy')->name('user.delete');

        /* Location Management */
        Route::get('/location', 'LocationController@index')->name('location.index');
        Route::get('/location/edit/{id?}/', 'LocationController@edit')->name('location.edit');
        Route::post('/location/store/{id?}', 'LocationController@store')->name('location.store');
        Route::get('/location/show/{id}', 'LocationController@show')->name('location.show');
        Route::post('/location/assign-user/{id?}', 'LocationController@assignUser')->name('location.assign-user');
        Route::get('/location/export', 'LocationController@export')->name('location.export');
        Route::post('/location/import', 'LocationController@import')->name('location.import');

        /* Product Management */
        Route::get('/product', 'ProductController@index')->name('product.index');
        Route::get('/product/create/{id?}', 'ProductController@create')->name('product.createOrEdit');
        Route::get('/product/show/{id}', 'ProductController@show')->name('product.show');
        Route::get('/product/export', 'ProductController@export')->name('product.export');
        Route::post('/product/import', 'ProductController@import')->name('product.import');

        /* Shipments */
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipment/show/{id}', 'ShipmentController@show')->name('shipment.show');
        Route::get('/shipment/change-status', 'ShipmentController@changeStatus')->name('shipment.change-status');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');
        Route::get('shipments/export', 'ShipmentController@export')->name('shipment.export');
        Route::get('shipments/cancel-shipments', 'ShipmentController@cancelShipmentIndex')->name('shipment.cancelShipments');

        /* Payouts */
        Route::get('/payouts/{status}', 'PayoutController@index')->name('payout.index');
        Route::get('/payouts/{id}/checkout', 'PayoutController@processCheckout')->name('payout.checkout');
        Route::get('/payouts/show/{id}', 'PayoutController@show')->name('payout.show');
    });

    Route::group(['prefix' => 'vendor', 'as' => 'vendor.', 'namespace' => 'Vendor', 'middleware' => ['role:vendor']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');
        Route::get('/no-locations', 'DashboardController@noLocations')->name('no-locations');

        // Trade-Ins Management
        Route::get('trade-ins', 'ShipmentController@tradeIns')->name('shipment.trade-ins');
        Route::get('trade-ins/show/{id}/', 'ShipmentController@tradeInShow')->name('shipment.trade-ins.show');

        // Shipment Management
        Route::get('shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
        Route::get('shipments/download-label/{id}', 'ShipmentController@downloadLabel')->name('shipment.download.label');
        Route::post('shipments/group-shipments', 'ShipmentController@groupShipments')->name('shipment.group-shipments');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');


        Route::get('/location/change/{id}', 'DashboardController@changeLocation')->name('location.change');

        Route::get('/shipments/approve-process/{id}', 'ShipmentController@approveProcess')->name('shipment.approveProcess');

        Route::get('/shipment-create', 'ShipmentController@createShipment')->name('shipment.create');
    });

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        //Change Password
        Route::get('/password/change', 'DashboardController@changePasswordIndex')->name('password.change.index');
        Route::post('/change-password', 'DashboardController@changePassword')->name('password.change');

        // Shipment Management
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
    });


    Route::group(['namespace' => 'Frontend'], function () {
        Route::get('/sell-your-device', 'SellDeviceController@index')->name('sell-your-device');
        Route::get('/shipment-process', 'SellDeviceController@shippingInformation')->name('shipment-process');
        Route::get('/shipment-review', 'SellDeviceController@shipmentReview')->name('shipment-review');
        Route::post('/confirm-location', 'SellDeviceController@confirmLocation')->name('confirm-location');
        Route::get('/ship-my-item', 'SellDeviceController@shipMyItemIndex')->name('ship-my-item');
        Route::get('/print-my-label', 'SellDeviceController@printMyLabelIndex')->name('print-my-label.index');
        Route::get('/print-my-label/download', 'SellDeviceController@printMyLabel')->name('print-my-label');
        Route::get('/cart', 'SellDeviceController@cart')->name('cart');
    });

    /* Contact Us */
    Route::get('contact-us', 'ContactUsController@index')->name('contact-us');
    Route::post('contact-us/store', 'ContactUsController@store')->name('contact-us.store');
    Route::post('buy-a-device-inquiry/store', 'ContactUsController@storeInquiry')->name('buy-a-device.inquiry.store');

    /** Request a free quote & Have a qustions*/
    Route::post('corporate-recycling/form/submit', 'ContactUsController@submitQuoteForm')->name('corporate-recycling.submit');
    Route::get('corporate-recycling/thank-you', 'ContactUsController@thankYouPage')->name('corporate-recycling.thankyou');

    /* Track Shipment */
    Route::get('/track-shipment', 'FrontendController@trackShipmentForm')->name('track-shipment');

    /* Sell Iphone */
    Route::get('/sell-iphone', 'FrontendController@sellIphone')->name('sell-iphone');
});

Route::group(['namespace' => 'App\Http\Livewire\Frontend'], function () {
    Route::get('/locations', Locations::class)->name('locations');
});

/*CMS Page */
Route::get('/{slug}', 'App\Http\Controllers\FrontendController@cmsPages')->name('cms-page');

Route::get('shipment-list', function () {
    return view('frontend.shipment-list');
})->name('shipment-list');

Route::get('shipment-detail/{id?}', function () {
    return view('frontend.shipment-detail');
})->name('shipment-detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/Frontend/SellDeviceController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Helpers\AppHelper;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Location;
use App\Models\Shipment;
use App\Models\User;
use App\Shipment\Shipment as ShipmentTrait;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use DNS2D;

class SellDeviceController extends Controller
{
    use ShipmentTrait;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('frontend.sell-your-device', compact('categories'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function shippingInformation()
    {
        $data = Session::get('data') ?? [];
        if ($data) {
            return view('frontend.shipping', compact('data'));
        }
        return redirect()->route('sell-your-device');
    }

    public function shipmentReview()
    {
        $data = Session::get('data') ?? [];
        $shipmentData = Session::get('shipmentData') ?? [];
        if ($data && $shipmentData) {
            $locationId = Session::get('location_id') ?? '';
            $location = Location::find($locationId);
            $user = User::getUser();
            $address = $location ?? $user->addresses()->where('status', '1')->first();
            return view('frontend.shipment-review', compact('data', 'address', 'user', 'shipmentData'));
        }
        return redirect()->route('sell-your-device');
    }

    public function confirmLocation()
    {
        $user = User::getUser();
        $data = Session::get('data') ?? [];
        $shipmentData = Session::get('shipmentData') ?? [];
        if ($user && $data && $shipmentData) {
            DB::beginTransaction();
            try {
                $uuId = $this->getUuid();
                $lastShipment = Shipment::orderBy('id', 'desc')->first();
                $shipmentNo = $lastShipment ? $lastShipment->shipment_no + 1 : '1001';
                $shipmentID = $lastShipment ? $lastShipment->id + 1 : '1';
                $totalPrice = AppHelper::getGrandTotal($data, $shipmentData['shipment_type']);
                $qrCode = $this->getQrCode($uuId, $shipmentID);
                $barcode = $this->getBarcode($shipmentID);
                $shipemtArr = [
                    'user_id' => $user->id,
                    'location_id' => $shipmentData['shipment_type'] == 1 ? $this->getLocation()->id : null,
                    'address_id' => $this->getAddress()->id,
                    'payout_method_id' => $shipmentData['userPayoutMethodId'] ?? null,
                    'total' => round($totalPrice, 2),
                    'sub_total' => round($totalPrice, 2),
                    'shipment_type' => $shipmentData['shipment_type'],
                    'qrcode' => $qrCode,
                    'barcode' => $barcode,
                    'label_url' => '',
                    'uuid' => $uuId,
                    'shipment_no' => $shipmentNo,
                    'tax' => 0,
                ];

                $shipmentItemData = [];

                foreach ($data as $key => $product) {
                    $price = $shipmentData['shipment_type'] == 1 ? $product['sku_retail_price'] : $product['sku_price'];
                    for ($i = 0; $i < $product['quantity']; $i++) {
                        $shipmentItemData[] = [
                            'sku_id' => $product['filtered_sku_id'],
                            'price' => round($price, 2),
                            'quantity' => 1,
                        ];
                    }
                }

                $shipment = $this->create($shipemtArr, $shipmentItemData);

                DB::commit();

                Session::forget('data');
                Session::forget('location_id');
                Session::forget('searched_location');
                Session::forget('shipmentData');

                AppHelper::notify('Your shipment has been created successfully', 'success');
                if ($shipment->shipment_type == '1') {
                    return redirect()->route('ship-my-item');
                } else {
                    return redirect()->route('print-my-label.index');
                }
            } catch (\Exception $e) {
                DB::rollBack();
                throw $e;
            }
        }

        return redirect()->route('sell-your-device');
    }

    public function shipMyItemIndex()
    {
        $shipment = $this->getShipment();
        if ($shipment) {
            $location = $shipment->location;
            return view('frontend.ship-my-item', compact('shipment', 'location'));
        }
        return redirect()->route('sell-your-device');
    }

    public function printMyLabelIndex()
    {
        $shipment = $this->getShipment();
        $user = User::getUser();
        if ($shipment && $user) {
            $address = $user->addresses()->where('status', '1')->first();
            return view('frontend.print-my-label', compact('shipment', 'address'));
        }
        return redirect()->route('sell-your-device');
    }

    public function printMyLabel()
    {
        $shipment = $this->getShipment();
        $filename = 'Shipment_' . $shipment->uuid . '.pdf';
        $tempImage = tempnam(sys_get_temp_dir(), $filename);
        copy($shipment->label_url, $tempImage);
        return response()->download($tempImage, $filename);
    }

    public function getUUID()
    {
        return AppHelper::uuid();
    }

    public function getQrCode($uuId, $shipmentID)
    {
        $path = public_path('/qrcodes/' . $uuId);
        if (!\File::isDirectory($path)) {
            \File::makeDirectory($path, 0777, true, true);
        }
        base64_encode(QrCode::format('png')->size(300)->generate($uuId, $path . '/barcode-' . $shipmentID . '.png'));
        return '/qrcodes/' . $uuId . '/barcode-' . $shipmentID . '.png';
    }

    public function getBarcode($shipmentID)
    {
        return DNS2D::getBarcodePNG($shipmentID, 'PDF417');
    }

    public function generatePdf()
    {
        // $path = public_path('/pdfs/' . $shipment->uuid);
        // if (!\File::isDirectory($path)) {
        //     \File::makeDirectory($path, 0777, true, true);
        // }
        // $data = [
        //     'address' => $address,
        //     'shipment' => $shipment,
        // ];
        // try {
        //     $pdf = PDF::loadView('frontend.pdf.print-label', $data)->save($path . '/label-' . $shipment->id . '.pdf');
        //     return $pdf;
        // } catch (\Exception $e) {
        //     throw $e;
        // }
    }

    public function getLocation()
    {
        $locationId = Session::get('location_id') ?? '';
        return Location::find($locationId);
    }

    public function getShipment()
    {
        $shipmentId = Session::get('shipment_id') ?? '';
        return Shipment::find($shipmentId);
    }

    public function getAddress()
    {
        $user = User::getUser();
        return $user->addresses()->where('status', '1')->first();
    }

    public function cart()
    {
        $data = Session::get('data') ?? [];
        if ($data) {
            return view('frontend.cart', compact('data'));
        }
        return redirect()->route('sell-your-device');
    }
}

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Models\Brand;
use App\Models\Category;
use Illuminate\Http\Request;

class FrontendController extends Controller
{
    public function trackShipmentForm()
    {
        return view('frontend.track-shipment');
    }

    public function sellIphone()
    {
        $category = Category::where('slug', 'phones')->first();
        $brand = Brand::where('slug', 'apple')->first();
        return view('frontend.sell-iphone', compact('category', 'brand'));
    }

    public function cmsPages(Request $request)
    {
        $slug = $request->slug;
        if (!in_array($slug, ['our-story', 'do-good', 'press', 'corporate-recycling', 'help-center', 'terms-condition', 'privacy-policy', 'retail-partners', 'buy-a-device', 'how-does-it-works'])) {
            abort(404);
        }
        return view('frontend.cms_pages.master', compact('slug'));
    }
}

app/Http/Livewire/Frontend/OrderSummary.php
<?php

namespace App\Http\Livewire\Frontend;

use Livewire\Component;

class OrderSummary extends Component
{
    public array $data = [];
    public $shipmentType;

    public function mount($data,$shipmentType)
    {
        $this->data = $data;
        $this->shipmentType = $shipmentType;
    }

    public function render()
    {
        return view('livewire.frontend.order-summary');
    }
}

resources/views/frontend/layouts/header.blade.php
<header class="header-wrapper">
    <nav class="navbar navbar-expand-lg bg-white" aria-label="Offcanvas navbar large">
        <div class="container-fluid ps-4 pe-4">
            <button class="navbar-toggler text-black btn-outline-none mobile-navbar-btn" type="button"
                data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar2" aria-controls="offcanvasNavbar2">
                <i class="text-black bx bx-menu"></i>
            </button>
            <a href="/"
                class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none header-logo">
                <img src="{{ asset('/assets/images/logos/gizmogul-logo.png') }}" alt="" height="17">
            </a>
            <div class="mobile-cart-user-wrapper">
                <div class="d-flex text-end align-items-center">
                    <a href="{{ route('login') }}" class="me-2 text-black fs-4"> <i class="bx bx-user"></i></a>
                    <a href="#" class="text-black fs-4"><i class="bx bx-shopping-bag"></i></a>
                </div>
            </div>
            <div class="offcanvas offcanvas-end text-black mobile-menu-wrapper" tabindex="-1" id="offcanvasNavbar2"
                aria-labelledby="offcanvasNavbar2Label">
                <div class="offcanvas-header border-bottom">
                    <a href="/"
                        class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none header-logo">
                        <img src="{{ asset('/assets/images/logos/gizmogul-logo.png') }}" alt="" height="17">
                    </a>
                    <button type="button" class="btn-close btn-close-black" data-bs-dismiss="offcanvas"
                        aria-label="Close"><i class="bx bx-x"></i></button>
                </div>
                <div class="offcanvas-body mobile-menu-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-5">
                        <li><a href="{{ route('cms-page', ['how-does-it-works']) }}" class="nav-link px-2 text-black">How does it works?</a></li>
                        <li><a href="{{ route('cms-page', ['corporate-recycling']) }}"
                                class="nav-link px-2 text-black">Enterprise Bulk Purchasing</a></li>
                        <li><a href="{{ route('cms-page', ['buy-a-device']) }}" class="nav-link px-2 text-black">Buy a
                                Device</a></li>
                        <a href="{{ route('sell-your-device') }}" role="button"
                            class="btn btn-primary text-white px-4 rounded-pill ms-lg-3 fw-bold">
                            Sell Your Device
                        </a>
                    </ul>
                    <div class="d-flex text-end align-items-center desktop-show-cart">
                        @if (!auth()->check())
                            <ul class="navbar-nav justify-content-end flex-grow-1 pe-1 sign-in-link">
                                <li><a href="{{ route('login') }}" class="nav-link px-2 text-black">Sign In</a></li>
                            </ul>
                        @endif
                        <div class="user-login-wrapper user-logged-in-links">
                            @if (auth()->check())
                                <a href="javascript:;" class="me-2 text-black fs-4 user-login-toggle"> <i
                                        class="bx bx-user"></i></a>
                                <ul class="user-select-menu">
                                    <li>
                                        <a href="{{ route('user.dashboard') }}">
                                            <i class="fas fa-home fa-sm fa-fw mr-2 orange-color"></i>
                                            {{ __('Dashboard') }}
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ route('user.password.change.index') }}">
                                            <i class="fas fa-key fa-sm fa-fw mr-2 orange-color"></i>
                                            {{ __('Change Password') }}
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ route('logout') }}">
                                            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 orange-color"></i>
                                            {{ __('Logout') }}
                                        </a>
                                    </li>
                                </ul>
                            @else
                                <a href="{{ route('login') }}" class="me-2 text-black fs-4"> <i
                                        class="bx bx-user"></i></a>
                            @endif
                        </div>
                        <a href="{{ route('cart') }}" class="text-black fs-4 cart-icon">
                            <i class="bx bx-shopping-bag"></i>
                            <span class="count-cartQty">{{ AppHelper::getCartQty() }}</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div class="mobile-search">
        <form action="">
            <div class="p-1 bg-light rounded mt-3">
                <div class="input-group">
                    <input type="search" placeholder="Search your product" aria-describedby="button-addon1"
                        class="form-control border-0 bg-light">
                    <div class="input-group-append">
                        <button id="button-addon1" type="submit" class="btn btn-link text-primary"><i
                                class="fa fa-search"></i></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</header>

resources/views/frontend/layouts/master.blade.php
<!doctype html>
<html lang="en">

<head>
    <title>@yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/assets/libs/owl.carousel/assets/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/assets/libs/owl.carousel/assets/owl.theme.default.min.css') }}">
    <!-- Icons Css -->
    <link href="{{ asset('/assets/css/icons.min.css') }}" rel="stylesheet" type="text/css" />

    <!-- Custome Css -->
    <link rel="stylesheet" href="{{ asset('frontend/css/custom.css') }}">
    <!-- Custome Css End -->

    <!-- responsive Css -->
    <link rel="stylesheet" href="{{ asset('frontend/css/responsive.css') }}">
    <!-- responsive Css End -->

    @livewireStyles

    @stack('styles')
    
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MSWJ8KS');</script>
<!-- End Google Tag Manager -->    
</head>

<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MSWJ8KS"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

    @flasher_render({limit:1})

    <!-- Header -->
    @include('frontend.layouts.header')
    <!-- End sHeader -->

    <!-- Home Page Slider -->
    <div class="owl-carousel header-top-slider owl-theme banner-top-slider">
        <div class="item">
            <h4>Excellent</h4>
            <img src="{{ asset('/assets/images/star-top.png') }}" alt="" height="17">
        </div>
        <div class="item">
            <h4>Excellent</h4>
            <img src="{{ asset('/assets/images/star-top.png') }}" alt="" height="17">
        </div>
        <div class="item">
            <h4>Excellent</h4>
            <img src="{{ asset('/assets/images/star-top.png') }}" alt="" height="17">
        </div>
    </div>
    <!-- Home Page Slider End -->

    <!-- Main Content -->
    @yield('content')
    {{ isset($slot) ? $slot : '' }}
    <!-- End Main Content -->

    <!-- Footer -->
    @include('frontend.layouts.footer')
    <!-- End Footer -->

    @livewireScripts

    @stack('scripts')

    <script src="{{ asset('frontend/js/homeInit.js') }}"></script>

</body>

</html>