routes/web.php
<?php

use App\Models\Shipment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

// Route::get('/mail', function () {
//     $shipment = Shipment::find(16);
//     $mailType = 'vendor';
//     return view('email.free-quote-mail', compact('shipment', 'mailType'));
// });



Route::group(['namespace' => 'App\Http\Controllers'], function () {
    Route::get('/autologin', 'Auth\LoginController@autoLogin');

    Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        /* User Management */
        Route::get('/users', 'UserController@index')->name('user.index');
        Route::get('/user/login/{id}', 'UserController@userLogin')->name('user.login');
        Route::get('/user/logout/', 'UserController@userLogout')->name('user.logout');
        Route::get('/user/create/{id?}', 'UserController@createOrEdit')->name('user.createOrEdit');
        Route::post('/user/store/{id?}', 'UserController@store')->name('user.store');
        Route::delete('/user/{id}/destroy', 'UserController@destroy')->name('user.delete');

        /* Location Management */
        Route::get('/location', 'LocationController@index')->name('location.index');
        Route::get('/location/edit/{id?}/', 'LocationController@edit')->name('location.edit');
        Route::post('/location/store/{id?}', 'LocationController@store')->name('location.store');
        Route::get('/location/show/{id}', 'LocationController@show')->name('location.show');
        Route::post('/location/assign-user/{id?}', 'LocationController@assignUser')->name('location.assign-user');
        Route::get('/location/export', 'LocationController@export')->name('location.export');
        Route::post('/location/import', 'LocationController@import')->name('location.import');

        /* Product Management */
        Route::get('/product', 'ProductController@index')->name('product.index');
        Route::get('/product/create/{id?}', 'ProductController@create')->name('product.createOrEdit');
        Route::get('/product/show/{id}', 'ProductController@show')->name('product.show');
        Route::get('/product/export', 'ProductController@export')->name('product.export');
        Route::post('/product/import', 'ProductController@import')->name('product.import');

        /* Shipments */
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipment/show/{id}', 'ShipmentController@show')->name('shipment.show');
        Route::get('/shipment/change-status', 'ShipmentController@changeStatus')->name('shipment.change-status');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');
        Route::get('shipments/export', 'ShipmentController@export')->name('shipment.export');
        Route::get('shipments/cancel-shipments', 'ShipmentController@cancelShipmentIndex')->name('shipment.cancelShipments');

        /* Payouts */
        Route::get('/payouts/{status}', 'PayoutController@index')->name('payout.index');
        Route::get('/payouts/{id}/checkout', 'PayoutController@processCheckout')->name('payout.checkout');
        Route::get('/payouts/show/{id}', 'PayoutController@show')->name('payout.show');
    });

    Route::group(['prefix' => 'vendor', 'as' => 'vendor.', 'namespace' => 'Vendor', 'middleware' => ['role:vendor']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');
        Route::get('/no-locations', 'DashboardController@noLocations')->name('no-locations');

        // Trade-Ins Management
        Route::get('trade-ins', 'ShipmentController@tradeIns')->name('shipment.trade-ins');
        Route::get('trade-ins/show/{id}/', 'ShipmentController@tradeInShow')->name('shipment.trade-ins.show');

        // Shipment Management
        Route::get('shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
        Route::get('shipments/download-label/{id}', 'ShipmentController@downloadLabel')->name('shipment.download.label');
        Route::post('shipments/group-shipments', 'ShipmentController@groupShipments')->name('shipment.group-shipments');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');


        Route::get('/location/change/{id}', 'DashboardController@changeLocation')->name('location.change');

        Route::get('/shipments/approve-process/{id}', 'ShipmentController@approveProcess')->name('shipment.approveProcess');

        Route::get('/shipment-create', 'ShipmentController@createShipment')->name('shipment.create');
    });

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        //Change Password
        Route::get('/password/change', 'DashboardController@changePasswordIndex')->name('password.change.index');
        Route::post('/change-password', 'DashboardController@changePassword')->name('password.change');

        // Shipment Management
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
    });


    Route::group(['namespace' => 'Frontend'], function () {
        Route::get('/sell-your-device', 'SellDeviceController@index')->name('sell-your-device');
        Route::get('/shipment-process', 'SellDeviceController@shippingInformation')->name('shipment-process');
        Route::get('/shipment-review', 'SellDeviceController@shipmentReview')->name('shipment-review');
        Route::post('/confirm-location', 'SellDeviceController@confirmLocation')->name('confirm-location');
        Route::get('/ship-my-item', 'SellDeviceController@shipMyItemIndex')->name('ship-my-item');
        Route::get('/print-my-label', 'SellDeviceController@printMyLabelIndex')->name('print-my-label.index');
        Route::get('/print-my-label/download', 'SellDeviceController@printMyLabel')->name('print-my-label');
        Route::get('/cart', 'SellDeviceController@cart')->name('cart');
    });

    /* Contact Us */
    Route::get('contact-us', 'ContactUsController@index')->name('contact-us');
    Route::post('contact-us/store', 'ContactUsController@store')->name('contact-us.store');
    Route::post('buy-a-device-inquiry/store', 'ContactUsController@storeInquiry')->name('buy-a-device.inquiry.store');

    /** Request a free quote & Have a qustions*/
    Route::post('corporate-recycling/form/submit', 'ContactUsController@submitQuoteForm')->name('corporate-recycling.submit');
    Route::get('corporate-recycling/thank-you', 'ContactUsController@thankYouPage')->name('corporate-recycling.thankyou');

    /* Track Shipment */
    Route::get('/track-shipment', 'FrontendController@trackShipmentForm')->name('track-shipment');

    /* Sell Iphone */
    Route::get('/sell-iphone', 'FrontendController@sellIphone')->name('sell-iphone');
});

Route::group(['namespace' => 'App\Http\Livewire\Frontend'], function () {
    Route::get('/locations', Locations::class)->name('locations');
});

/*CMS Page */
Route::get('/{slug}', 'App\Http\Controllers\FrontendController@cmsPages')->name('cms-page');

Route::get('shipment-list', function () {
    return view('frontend.shipment-list');
})->name('shipment-list');

Route::get('shipment-detail/{id?}', function () {
    return view('frontend.shipment-detail');
})->name('shipment-detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Http/Controllers/Admin/ShipmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Actions\ChangeShipmentStatusAction;
use App\Actions\CreateUserPayoutAction;
use App\Helpers\AppHelper;
use App\Http\Controllers\Controller;
use App\Models\Shipment;
use Illuminate\Http\Request;

class ShipmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $shipments = Shipment::whereNotIn('status', ['cancel'])->with('user', 'location', 'shipmentItems', 'shipmentItems.sku')->orderBy('id', 'DESC')->get();
        return view('admin.shipments.index', compact('shipments'));
    }

    /**
     * Display a cancel shipment listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function cancelShipmentIndex()
    {
        $shipments = Shipment::where('status', 'cancel')->with('user', 'location', 'shipmentItems', 'shipmentItems.sku')->orderBy('id', 'DESC')->get();
        return view('admin.shipments.cancel-shipment-index', compact('shipments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shipment = Shipment::with(['shipmentItems', 'shipmentItems.sku'])->findOrFail($id);
        return view('admin.shipments.show', compact('shipment'));
    }

    public function changeStatus(Request $request)
    {
        $shipment = Shipment::findOrFail($request->id);

        /** @var ChangeShipmentStatusAction $action */
        $action = app(ChangeShipmentStatusAction::class);
        $shipment = $action->execute($shipment, $request->status);

        if ($request->status == 'received') {
            $paymentId = AppHelper::uuid();
            /** @var CreateUserPayoutAction $action */
            $action = app(CreateUserPayoutAction::class);
            $action->execute($shipment, $paymentId);
        }

        return redirect()->back()->with('success', 'Status changed successfully');
    }

    public function cancelShipment($id)
    {
        $shipment = Shipment::findOrFail($id);
        $shipment->status = 'cancel';
        $shipment->save();
        return redirect()->back()->with('success', 'Shipment cancelled successfully');
    }

    /**
     * Export the location
     */
    public function export()
    {
        $fileName = 'Shipment_' . date("Y-m-d") . '.csv';
        $shipments = Shipment::get()->map(function ($shipment) {
            return [
                'shipment_no' => $shipment->shipment_no,
                'billing_name' => $shipment->user->name,
                'date' => date('m/d/Y, g:ia', strtotime($shipment->created_at)),
                'commission' => '$' . number_format($shipment->commission, 2),
                'total' => '$' . number_format($shipment->total, 2),
                'total_qty' => $this->getTotakQty($shipment),
                'status' => ucfirst($shipment->status),
                'shipping_method' => $this->getShippingMethod($shipment),
            ];
        })->toArray();

        $columns = $this->getShipmentsCsvHeader();
        $callback = function () use ($columns, $shipments) {
            $file = fopen('php://output', 'w');
            fputcsv($file, $columns);

            foreach ($shipments as $key => $row) {
                fputcsv($file, $row);
            }

            fclose($file);
        };
        return response()->stream($callback, 200, ["Content-type" => "text/csv", "Content-Disposition" => "attachment; filename=$fileName", "Pragma" => "no-cache", "Cache-Control" => "must-revalidate, post-check=0, pre-check=0", "Expires" => "0"]);
    }

    public function getTotakQty($shipment)
    {
        if ($shipment->notes != '') {
            $shipments = Shipment::whereIn('id', explode(',', $shipment->notes['shipment_id']))->get();
            $qty = 0;
            foreach ($shipments as $shipment) {
                $qty += $shipment->shipmentItems->count();
            }
            return $qty;
        } else {
            return $shipment->shipmentItems()->sum('quantity');
        }
    }

    public function getShippingMethod($shipment)
    {
        if ($shipment->shipment_type == 1) {
            return 'Drop-off';
        } else {
            return 'Ship';
        }
    }

    public function getShipmentsCsvHeader()
    {
        return ['Shipment No #', 'Billing Name', 'Date', 'Commission', 'Total', 'Total QTY', 'Status', 'Shipping Method'];
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Shipment;
use App\Models\UserPayout;
use App\Rules\ValidateOldPassword;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class DashboardController extends Controller
{
    /**
     * Return View.
     *
     * @return void
     */
    public function index()
    {
        $tradeIns = Shipment::where('user_id', auth()->user()->id)->orderBy('id', 'desc')->limit(5)->get();
        $totalAmountReceived = UserPayout::where('user_id', auth()->user()->id)->orderBy('id', 'desc')->sum('amount');
        $tradeInsCount = Shipment::where('user_id', auth()->user()->id)->where('status', '!=', 'pending')->orderBy('id', 'desc')->count();
        return view('users.dashboard', compact('tradeIns', 'tradeInsCount', 'totalAmountReceived'));
    }

    public function changePasswordIndex()
    {
        return view('auth.passwords.change');
    }

    public function changePassword(Request $request)
    {
        $request->validate([
            'old_password' => ['required', new ValidateOldPassword()],
            'new_password' => ['required'],
            'password_confirmation' => ['same:new_password'],
        ]);
        $user = auth()->user();
        $status = $user->update(['password' => Hash::make($request->new_password)]);

        if ($status) {
            return redirect()->route('login')->with('success', "Your password has been changed successfully");
        } else {
            return redirect()->back()->with('error', "Error occurred while changing password");
        }
    }
}

app/Http/Controllers/User/ShipmentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;

class ShipmentController extends Controller
{
    public function index()
    {
        $shipments = auth()->user()->shipments;
        return view('users.shipments.index', compact('shipments'));
    }

    public function show($id)
    {
        $shipment = auth()->user()->shipments()->find($id);
        return view('users.shipments.show', compact('shipment'));
    }
}

app/View/Components/Frontend/ShipmentType.php
<?php

namespace App\View\Components\Frontend;

use App\Models\UserPayoutMethod;
use Illuminate\View\Component;

class ShipmentType extends Component
{
    public $shipmentType;
    public $payoutMethods;
    public $payoutMethod;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($shipmentType, $payoutMethod)
    {
        $this->shipmentType = $shipmentType;
        $this->payoutMethods = $this->getPayoutMethods();
        $this->payoutMethod = $payoutMethod;
    }

    public function getPayoutMethods()
    {
        return UserPayoutMethod::all();
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.frontend.shipment-type');
    }
}

resources/views/users/shipments/index.blade.php
@extends('layouts.user.master')
@section('title', 'GIZMOGUL || Shipments List')
@push('styles')
    <!-- DataTables -->
    <link href="{{ asset('/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{{ asset('/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />
@endpush
@section('main-content')
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Shipments List</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Shipments</a></li>
                            <li class="breadcrumb-item active">List</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table align-middle table-nowrap table-hover table table-bordered data-table">
                                <thead class="table-light">
                                    <tr>
                                        <th scope="col">Shipment No #</th>
                                        <th scope="col">Shipment Type</th>
                                        <th scope="col">Location Name</th>
                                        <th scope="col">Total ($)</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($shipments as $key => $shipment)
                                        <tr>
                                            <td> {{ $shipment->shipment_no }} </td>
                                            <td> {{ $shipment->shipment_type == 1 ? 'Drop off' : 'Ship' }} </td>
                                            <td> {{ $shipment->location->name ?? '' }} </td>
                                            <td> {{ $shipment->total ?? '' }} </td>
                                            <td>
                                                <div class="dropdown">
                                                    <a href="#" class="dropdown-toggle card-drop"
                                                        data-bs-toggle="dropdown" aria-expanded="false">
                                                        <i class="mdi mdi-dots-horizontal font-size-18"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-end">
                                                        <a class="dropdown-item"
                                                            href="{{ route('user.shipment.show', $shipment->id) }}">View</a>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script type="text/javascript">
        $(function() {
            $('.data-table').DataTable({
                "columnDefs": [{
                    "orderable": false,
                    "targets": [4]
                }, {
                    "targets": [0, 1, 2, 3, 4],
                    "className": "text-center",
                }],
                "order": [0, "desc"]
            });
        });
    </script>
@endpush

resources/views/users/shipments/show.blade.php
@extends('layouts.user.master')
@section('title', 'GIZMOGUL || Shipment Details')
@section('main-content')
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Shipment Detail</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Shipment</a></li>
                            <li class="breadcrumb-item active">Detail</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="invoice-title">
                            <h4 class="float-end font-size-16">Shipment # {{ $shipment->shipment_no }}</h4>
                            <div class="mb-4">
                                <img src="{{ asset('/assets/images/logos/gizmogul-logo.png') }}" alt="logo"
                                    height="20">
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-8">
                                <address class="mt-2 mt-sm-0">
                                    @if ($shipment->shipment_type != '1')
                                        <strong>Shipped To:</strong><br />
                                        <span>{{ $shipment->user->name }}</span><br />
                                        <span>{{ $shipment->address->address }}</span><br />
                                        @if ($shipment->address->apartment)
                                            <span>{{ $shipment->address->address }}</span><br />
                                        @endif
                                        <span>{{ $shipment->address->city . ', ' . $shipment->address->state . ' ' . $shipment->address->zip }}</span><br />
                                        <span>{{ $shipment->address->country->iso3 }}</span><br />
                                    @else
                                        <strong>Drop off to:</strong><br />
                                        <span>{{ $shipment->location->name }}</span><br />
                                        <span>{{ $shipment->location->address }}</span><br />
                                        @if ($shipment->location->address2)
                                            <span>{{ $shipment->location->address2 }}</span><br />
                                        @endif
                                        <span>{{ $shipment->location->city . ', ' . $shipment->location->state . ' ' . $shipment->location->zip }}</span><br />
                                    @endif
                                </address>
                            </div>
                            <div class="col-sm-4 text-sm-end">
                                <address>
                                    <strong>Shipment Date:</strong><br>
                                    {{ \Carbon\Carbon::parse($shipment->created_at)->format('F d, Y') }}<br><br>
                                </address>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 mt-3">
                                <address>
                                    <strong>Payment Method:</strong><br>
                                    @if ($shipment->userPayoutMethod)
                                        {{ $shipment->userPayoutMethod->name }}<br>
                                    @else
                                        Visa ending **** 4242<br>
                                        {{ $shipment->user->email }}
                                    @endif
                                </address>
                            </div>
                        </div>
                        <div class="py-2 mt-3">
                            <h3 class="font-size-15 fw-bold">Shipment summary</h3>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-nowrap">
                                <thead>
                                    <tr>
                                        <th style="width: 70px;">No.</th>
                                        <th>Item</th>
                                        <th>Price</th>
                                        <th>Qty</th>
                                        <th class="text-end">Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($shipment->shipmentItems as $key => $shipmentItem)
                                        <tr>
                                            <td>{{ $shipmentItem->id }}</td>
                                            <td>{{ $shipmentItem->sku->product->name }}</td>
                                            <td>
                                                ${{ $shipmentItem->price }}
                                            </td>
                                            <td>{{ $shipmentItem->quantity }}</td>
                                            <td class="text-end">
                                                ${{ number_format($shipmentItem->price * $shipmentItem->quantity, 2) }}
                                            </td>
                                        </tr>
                                    @endforeach
                                    <tr>
                                        <td colspan="4" class="text-end">Total</td>
                                        <td class="text-end">${{ $shipment->sub_total }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="4" class="border-0 text-end">
                                            <strong>Tax</strong>
                                        </td>
                                        <td class="border-0 text-end">${{ $shipment->tax }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="4" class="border-0 text-end">
                                            <strong>Grand Total</strong>
                                        </td>
                                        <td class="border-0 text-end">
                                            <h4 class="m-0">${{ $shipment->total }}</h4>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="d-print-none">
                            <div class="float-end">
                                <a href="javascript:window.print()" class="btn btn-primary waves-effect waves-light me-1"><i
                                        class="fa fa-print"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
@endsection