routes/web.php
<?php

use App\Models\Shipment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
});

Auth::routes();

// Route::get('/mail', function () {
//     $shipment = Shipment::find(16);
//     $mailType = 'vendor';
//     return view('email.free-quote-mail', compact('shipment', 'mailType'));
// });



Route::group(['namespace' => 'App\Http\Controllers'], function () {
    Route::get('/autologin', 'Auth\LoginController@autoLogin');

    Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['role:admin']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        /* User Management */
        Route::get('/users', 'UserController@index')->name('user.index');
        Route::get('/user/login/{id}', 'UserController@userLogin')->name('user.login');
        Route::get('/user/logout/', 'UserController@userLogout')->name('user.logout');
        Route::get('/user/create/{id?}', 'UserController@createOrEdit')->name('user.createOrEdit');
        Route::post('/user/store/{id?}', 'UserController@store')->name('user.store');
        Route::delete('/user/{id}/destroy', 'UserController@destroy')->name('user.delete');

        /* Location Management */
        Route::get('/location', 'LocationController@index')->name('location.index');
        Route::get('/location/edit/{id?}/', 'LocationController@edit')->name('location.edit');
        Route::post('/location/store/{id?}', 'LocationController@store')->name('location.store');
        Route::get('/location/show/{id}', 'LocationController@show')->name('location.show');
        Route::post('/location/assign-user/{id?}', 'LocationController@assignUser')->name('location.assign-user');
        Route::get('/location/export', 'LocationController@export')->name('location.export');
        Route::post('/location/import', 'LocationController@import')->name('location.import');

        /* Product Management */
        Route::get('/product', 'ProductController@index')->name('product.index');
        Route::get('/product/create/{id?}', 'ProductController@create')->name('product.createOrEdit');
        Route::get('/product/show/{id}', 'ProductController@show')->name('product.show');
        Route::get('/product/export', 'ProductController@export')->name('product.export');
        Route::post('/product/import', 'ProductController@import')->name('product.import');

        /* Shipments */
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipment/show/{id}', 'ShipmentController@show')->name('shipment.show');
        Route::get('/shipment/change-status', 'ShipmentController@changeStatus')->name('shipment.change-status');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');
        Route::get('shipments/export', 'ShipmentController@export')->name('shipment.export');
        Route::get('shipments/cancel-shipments', 'ShipmentController@cancelShipmentIndex')->name('shipment.cancelShipments');

        /* Payouts */
        Route::get('/payouts/{status}', 'PayoutController@index')->name('payout.index');
        Route::get('/payouts/{id}/checkout', 'PayoutController@processCheckout')->name('payout.checkout');
        Route::get('/payouts/show/{id}', 'PayoutController@show')->name('payout.show');
    });

    Route::group(['prefix' => 'vendor', 'as' => 'vendor.', 'namespace' => 'Vendor', 'middleware' => ['role:vendor']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');
        Route::get('/no-locations', 'DashboardController@noLocations')->name('no-locations');

        // Trade-Ins Management
        Route::get('trade-ins', 'ShipmentController@tradeIns')->name('shipment.trade-ins');
        Route::get('trade-ins/show/{id}/', 'ShipmentController@tradeInShow')->name('shipment.trade-ins.show');

        // Shipment Management
        Route::get('shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
        Route::get('shipments/download-label/{id}', 'ShipmentController@downloadLabel')->name('shipment.download.label');
        Route::post('shipments/group-shipments', 'ShipmentController@groupShipments')->name('shipment.group-shipments');
        Route::post('shipments/{id}/cancel', 'ShipmentController@cancelShipment')->name('shipment.cancel');


        Route::get('/location/change/{id}', 'DashboardController@changeLocation')->name('location.change');

        Route::get('/shipments/approve-process/{id}', 'ShipmentController@approveProcess')->name('shipment.approveProcess');

        Route::get('/shipment-create', 'ShipmentController@createShipment')->name('shipment.create');
    });

    Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User', 'middleware' => ['auth']], function () {
        Route::get('/dashboard', 'DashboardController@index')->middleware('permission:dashboard_access')->name('dashboard');

        //Change Password
        Route::get('/password/change', 'DashboardController@changePasswordIndex')->name('password.change.index');
        Route::post('/change-password', 'DashboardController@changePassword')->name('password.change');

        // Shipment Management
        Route::get('/shipments', 'ShipmentController@index')->name('shipment.index');
        Route::get('/shipments/show/{id}/', 'ShipmentController@show')->name('shipment.show');
    });


    Route::group(['namespace' => 'Frontend'], function () {
        Route::get('/sell-your-device', 'SellDeviceController@index')->name('sell-your-device');
        Route::get('/shipment-process', 'SellDeviceController@shippingInformation')->name('shipment-process');
        Route::get('/shipment-review', 'SellDeviceController@shipmentReview')->name('shipment-review');
        Route::post('/confirm-location', 'SellDeviceController@confirmLocation')->name('confirm-location');
        Route::get('/ship-my-item', 'SellDeviceController@shipMyItemIndex')->name('ship-my-item');
        Route::get('/print-my-label', 'SellDeviceController@printMyLabelIndex')->name('print-my-label.index');
        Route::get('/print-my-label/download', 'SellDeviceController@printMyLabel')->name('print-my-label');
        Route::get('/cart', 'SellDeviceController@cart')->name('cart');
    });

    /* Contact Us */
    Route::get('contact-us', 'ContactUsController@index')->name('contact-us');
    Route::post('contact-us/store', 'ContactUsController@store')->name('contact-us.store');
    Route::post('buy-a-device-inquiry/store', 'ContactUsController@storeInquiry')->name('buy-a-device.inquiry.store');

    /** Request a free quote & Have a qustions*/
    Route::post('corporate-recycling/form/submit', 'ContactUsController@submitQuoteForm')->name('corporate-recycling.submit');
    Route::get('corporate-recycling/thank-you', 'ContactUsController@thankYouPage')->name('corporate-recycling.thankyou');

    /* Track Shipment */
    Route::get('/track-shipment', 'FrontendController@trackShipmentForm')->name('track-shipment');

    /* Sell Iphone */
    Route::get('/sell-iphone', 'FrontendController@sellIphone')->name('sell-iphone');
});

Route::group(['namespace' => 'App\Http\Livewire\Frontend'], function () {
    Route::get('/locations', Locations::class)->name('locations');
});

/*CMS Page */
Route::get('/{slug}', 'App\Http\Controllers\FrontendController@cmsPages')->name('cms-page');

Route::get('shipment-list', function () {
    return view('frontend.shipment-list');
})->name('shipment-list');

Route::get('shipment-detail/{id?}', function () {
    return view('frontend.shipment-detail');
})->name('shipment-detail');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

app/Models/Shipment.php
<?php

namespace App\Models;

use App\Helpers\AppHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shipment extends Model
{
    use HasFactory;

    protected $fillable = [
        'tax',
        'uuid',
        'total',
        'status',
        'qrcode',
        'barcode',
        'user_id',
        'sub_total',
        'label_url',
        'address_id',
        'location_id',
        'shipment_no',
        'shipment_type',
        'shipping_type',
        'payment_method',
        'payout_method_id',
        'tracking_no',
        'tracking_url',
        'shipping_carrier',
        'shipment_status',
        'notes',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function address()
    {
        return $this->belongsTo(UserAddress::class);
    }

    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    public function shipmentItems()
    {
        return $this->hasMany(ShipmentItem::class);
    }

    public function userPayoutMethod()
    {
        return $this->belongsTo(UserPayoutMethod::class, 'payout_method_id');
    }

    public function userPayout()
    {
        return $this->hasOne(UserPayout::class, 'shipment_id');
    }

    public static function shipmentCountByLocation($id)
    {
        return Shipment::where('location_id', $id)->count();
    }

    public function getNotesAttribute($value)
    {
        return json_decode($value, true);
    }

    public static function getShipments()
    {
        if (AppHelper::isUser()) {
            return Shipment::where('user_id', auth()->user()->id)->orderBy('id', 'desc');
        } else {
            return Shipment::orderBy('id', 'desc');
        }
    }
}

app/Http/Controllers/Admin/ShipmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Actions\ChangeShipmentStatusAction;
use App\Actions\CreateUserPayoutAction;
use App\Helpers\AppHelper;
use App\Http\Controllers\Controller;
use App\Models\Shipment;
use Illuminate\Http\Request;

class ShipmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $shipments = Shipment::whereNotIn('status', ['cancel'])->with('user', 'location', 'shipmentItems', 'shipmentItems.sku')->orderBy('id', 'DESC')->get();
        return view('admin.shipments.index', compact('shipments'));
    }

    /**
     * Display a cancel shipment listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function cancelShipmentIndex()
    {
        $shipments = Shipment::where('status', 'cancel')->with('user', 'location', 'shipmentItems', 'shipmentItems.sku')->orderBy('id', 'DESC')->get();
        return view('admin.shipments.cancel-shipment-index', compact('shipments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $shipment = Shipment::with(['shipmentItems', 'shipmentItems.sku'])->findOrFail($id);
        return view('admin.shipments.show', compact('shipment'));
    }

    public function changeStatus(Request $request)
    {
        $shipment = Shipment::findOrFail($request->id);

        /** @var ChangeShipmentStatusAction $action */
        $action = app(ChangeShipmentStatusAction::class);
        $shipment = $action->execute($shipment, $request->status);

        if ($request->status == 'received') {
            $paymentId = AppHelper::uuid();
            /** @var CreateUserPayoutAction $action */
            $action = app(CreateUserPayoutAction::class);
            $action->execute($shipment, $paymentId);
        }

        return redirect()->back()->with('success', 'Status changed successfully');
    }

    public function cancelShipment($id)
    {
        $shipment = Shipment::findOrFail($id);
        $shipment->status = 'cancel';
        $shipment->save();
        return redirect()->back()->with('success', 'Shipment cancelled successfully');
    }

    /**
     * Export the location
     */
    public function export()
    {
        $fileName = 'Shipment_' . date("Y-m-d") . '.csv';
        $shipments = Shipment::get()->map(function ($shipment) {
            return [
                'shipment_no' => $shipment->shipment_no,
                'billing_name' => $shipment->user->name,
                'date' => date('m/d/Y, g:ia', strtotime($shipment->created_at)),
                'commission' => '$' . number_format($shipment->commission, 2),
                'total' => '$' . number_format($shipment->total, 2),
                'total_qty' => $this->getTotakQty($shipment),
                'status' => ucfirst($shipment->status),
                'shipping_method' => $this->getShippingMethod($shipment),
            ];
        })->toArray();

        $columns = $this->getShipmentsCsvHeader();
        $callback = function () use ($columns, $shipments) {
            $file = fopen('php://output', 'w');
            fputcsv($file, $columns);

            foreach ($shipments as $key => $row) {
                fputcsv($file, $row);
            }

            fclose($file);
        };
        return response()->stream($callback, 200, ["Content-type" => "text/csv", "Content-Disposition" => "attachment; filename=$fileName", "Pragma" => "no-cache", "Cache-Control" => "must-revalidate, post-check=0, pre-check=0", "Expires" => "0"]);
    }

    public function getTotakQty($shipment)
    {
        if ($shipment->notes != '') {
            $shipments = Shipment::whereIn('id', explode(',', $shipment->notes['shipment_id']))->get();
            $qty = 0;
            foreach ($shipments as $shipment) {
                $qty += $shipment->shipmentItems->count();
            }
            return $qty;
        } else {
            return $shipment->shipmentItems()->sum('quantity');
        }
    }

    public function getShippingMethod($shipment)
    {
        if ($shipment->shipment_type == 1) {
            return 'Drop-off';
        } else {
            return 'Ship';
        }
    }

    public function getShipmentsCsvHeader()
    {
        return ['Shipment No #', 'Billing Name', 'Date', 'Commission', 'Total', 'Total QTY', 'Status', 'Shipping Method'];
    }
}

app/Http/Controllers/User/ShipmentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;

class ShipmentController extends Controller
{
    public function index()
    {
        $shipments = auth()->user()->shipments;
        return view('users.shipments.index', compact('shipments'));
    }

    public function show($id)
    {
        $shipment = auth()->user()->shipments()->find($id);
        return view('users.shipments.show', compact('shipment'));
    }
}

app/View/Components/Frontend/ShipmentType.php
<?php

namespace App\View\Components\Frontend;

use App\Models\UserPayoutMethod;
use Illuminate\View\Component;

class ShipmentType extends Component
{
    public $shipmentType;
    public $payoutMethods;
    public $payoutMethod;

    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct($shipmentType, $payoutMethod)
    {
        $this->shipmentType = $shipmentType;
        $this->payoutMethods = $this->getPayoutMethods();
        $this->payoutMethod = $payoutMethod;
    }

    public function getPayoutMethods()
    {
        return UserPayoutMethod::all();
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.frontend.shipment-type');
    }
}

resources/views/admin/shipments/index.blade.php
@extends('layouts.admin.master')
@section('title', 'GIZMOGUL || Shipments List')
@push('styles')
    <!-- DataTables -->
    <link href="{{ asset('/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />

    <!-- Responsive datatable examples -->
    <link href="{{ asset('/assets/libs/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('/assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endpush
@section('main-content')
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Shipments</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Shipments</a></li>
                            <li class="breadcrumb-item active">List</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->
        
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <!-- Export Csv Button -->
                            <div class="float-right mb-3 button-flex">
                                <a href="{{ route('admin.shipment.export') }}" class="btn btn-primary">
                                    <i class="bx bx-download me-2"></i>Export CSV
                                </a>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table
                                class="table align-middle table-nowrap table-hover table table-bordered data-table shipment-list-table">
                                <thead class="table-light">
                                    <tr>
                                        <th scope="align-middle">Shipment No #</th>
                                        <th class="align-middle">Billing Name</th>
                                        <th class="align-middle">Date</th>
                                        <th class="align-middle">Commission</th>
                                        <th class="align-middle">Total</th>
                                        <th class="align-middle">Total QTY</th>
                                        <th class="align-middle">Status</th>
                                        <th class="align-middle">Shipping Method</th>
                                        <th scope="align-middle">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($shipments as $key => $shipment)
                                        <tr>
                                            <td>
                                                <a href="{{ route('admin.shipment.show', $shipment->id) }}">
                                                    {{ $shipment->shipment_no }}
                                                </a>
                                            </td>
                                            <td>{{ $shipment->user->name }}</td>
                                            <td>
                                                {{ date('m/d/Y, g:ia', strtotime($shipment->created_at)) }}
                                            </td>
                                            <td>
                                                ${{ number_format($shipment->commission, 2) }}
                                            </td>
                                            <td>
                                                ${{ number_format($shipment->total, 2) }}
                                            </td>
                                            <td>
                                                @if ($shipment->notes != '')
                                                    @php
                                                        $shipments = App\Models\Shipment::whereIn('id', explode(',', $shipment->notes['shipment_id']))->get();
                                                        $qty = 0;
                                                        foreach ($shipments as $shipment) {
                                                            $qty += $shipment->shipmentItems->count();
                                                        }
                                                    @endphp

                                                    {{ $qty }}
                                                @else
                                                    {{ $shipment->shipmentItems()->sum('quantity') }}
                                                @endif
                                            </td>
                                            <td>
                                                @if ($shipment->status == 'pending')
                                                    <span class="badge badge-pill badge-soft-warning font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'approved')
                                                    <span class="badge badge-pill badge-soft-success font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'shipped')
                                                    <span class="badge badge-pill badge-soft-secondary font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'delivered')
                                                    <span class="badge badge-pill badge-soft-info font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'received')
                                                    <span class="badge badge-pill badge-soft-info font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'completed')
                                                    <span class="badge badge-pill badge-soft-success font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 're-packaged')
                                                    <span class="badge badge-pill badge-soft-primary font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'please-ship')
                                                    <span class="badge badge-pill badge-soft-pink font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @elseif($shipment->status == 'cancel')
                                                    <span class="badge badge-pill badge-soft-danger font-size-11">
                                                        {{ ucfirst($shipment->status) }}
                                                    </span>
                                                @endif
                                            </td>
                                            <td>
                                                @if ($shipment->shipment_type == 1)
                                                    <i class="fas fa-people-carry"></i> Drop-off <br>
                                                    @if ($shipment->location)
                                                        <a
                                                            href="{{ route('admin.location.show', $shipment->location_id) }}">{{ $shipment->location->name }},
                                                            {{ $shipment->location->city }},
                                                            {{ $shipment->location->state }}</a>
                                                    @endif
                                                @else
                                                    <i class="fas fa-barcode"></i> Ship
                                                @endif
                                            </td>
                                            <td>
                                                <div class="dropdown">
                                                    <a href="#" class="dropdown-toggle card-drop"
                                                        data-bs-toggle="dropdown" aria-expanded="false">
                                                        <i class="mdi mdi-dots-horizontal font-size-18"></i>
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-end">
                                                        <a class="dropdown-item"
                                                            href="{{ route('admin.shipment.show', $shipment->id) }}">View</a>
                                                        @if ($shipment->status == 'pending')
                                                            <form
                                                                action="{{ route('admin.shipment.cancel', $shipment->id) }}"
                                                                method="POST">
                                                                @csrf
                                                                <a class="dropdown-item cancel" href="javascript:;">Cancel</a>
                                                            </form>
                                                        @endif
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script src="{{ asset('/assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>
    <script type="text/javascript">
        $(function() {
            $('.data-table').DataTable({
                "columnDefs": [{
                    "orderable": false,
                    "targets": [8]
                }, {
                    "targets": [0, 1, 2, 3, 4, 5, 6, 7],
                    "className": "text-center",
                }],
                "order": [0, "desc"]
            });

            $('.cancel').on('click', function(e) {
                var form = $(this).closest('form');
                Swal.fire({
                    title: "Are you sure?",
                    text: "Want to cancel this shipment?",
                    icon: "error",
                    showCancelButton: !0,
                    cancelButtonColor: "#f46a6a",
                    cancelButtonText: "Cancel",
                    confirmButtonColor: "#34c38f",
                    confirmButtonText: "Submit",
                }).then(function(t) {
                    if (t.isConfirmed) {
                        form.submit();
                    }
                });
            });
        });
    </script>
@endpush